ktor:
  application:
    modules:
      - com.danceboard.backend.ApplicationKt.module
  deployment:
    port: 8080
datasource:
  jdbcUrl: "jdbc:postgresql://localhost:5432/danceboard"
  username: "danceboard"
  password: "danceboard"
  driverClassName: "org.postgresql.Driver"
  maxPoolSize: 5