ktor:
  application:
    modules:
      - com.danceboard.backend.ApplicationKt.module
  deployment:
    port: 8080
datasource:
  jdbcUrl: ${?DB_URL}
  username: ${?DB_USER}
  password: ${?DB_PASSWORD}
  driverClassName: "org.postgresql.Driver"
  maxPoolSize: 5

google:
  drive:
    folderId: ${?GOOGLE_DRIVE_FOLDER_ID}
    clientId: ${?GOOGLE_CLIENT_ID}
    clientSecret: ${?GOOGLE_CLIENT_SECRET}
    refreshToken: ${?GOOGLE_REFRESH_TOKEN}